export const REVALIDATE_ETAG_METADATA = Symbol('REVALIDATE_ETAG_METADATA');
export const REVALIDATE_LAST_MODIFIED_METADATA = Symbol('REVALIDATE_LAST_MODIFIED_METADATA');
export const REVALIDATE_CACHE_CONTROL_METADATA = Symbol('REVALIDATE_CACHE_CONTROL_METADATA');
export const REVALIDATE_VARY_METADATA = Symbol('REVALIDATE_VARY_METADATA');
export const REVALIDATE_NO_STORE_METADATA = Symbol('REVALIDATE_NO_STORE_METADATA');